// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.31.1
// source: service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TasksService_AddTask_FullMethodName          = "/tasks_pb.TasksService/AddTask"
	TasksService_RemoveTask_FullMethodName       = "/tasks_pb.TasksService/RemoveTask"
	TasksService_ListAllTasks_FullMethodName     = "/tasks_pb.TasksService/ListAllTasks"
	TasksService_MarkTaskFinished_FullMethodName = "/tasks_pb.TasksService/MarkTaskFinished"
)

// TasksServiceClient is the client API for TasksService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Tasks functions API
type TasksServiceClient interface {
	AddTask(ctx context.Context, in *TaskImportData, opts ...grpc.CallOption) (*TaskExportData, error)
	RemoveTask(ctx context.Context, in *TaskId, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListAllTasks(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TaskList, error)
	MarkTaskFinished(ctx context.Context, in *TaskId, opts ...grpc.CallOption) (*TaskExportData, error)
}

type tasksServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTasksServiceClient(cc grpc.ClientConnInterface) TasksServiceClient {
	return &tasksServiceClient{cc}
}

func (c *tasksServiceClient) AddTask(ctx context.Context, in *TaskImportData, opts ...grpc.CallOption) (*TaskExportData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskExportData)
	err := c.cc.Invoke(ctx, TasksService_AddTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tasksServiceClient) RemoveTask(ctx context.Context, in *TaskId, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TasksService_RemoveTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tasksServiceClient) ListAllTasks(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TaskList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskList)
	err := c.cc.Invoke(ctx, TasksService_ListAllTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tasksServiceClient) MarkTaskFinished(ctx context.Context, in *TaskId, opts ...grpc.CallOption) (*TaskExportData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskExportData)
	err := c.cc.Invoke(ctx, TasksService_MarkTaskFinished_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TasksServiceServer is the server API for TasksService service.
// All implementations must embed UnimplementedTasksServiceServer
// for forward compatibility.
//
// Tasks functions API
type TasksServiceServer interface {
	AddTask(context.Context, *TaskImportData) (*TaskExportData, error)
	RemoveTask(context.Context, *TaskId) (*emptypb.Empty, error)
	ListAllTasks(context.Context, *emptypb.Empty) (*TaskList, error)
	MarkTaskFinished(context.Context, *TaskId) (*TaskExportData, error)
	mustEmbedUnimplementedTasksServiceServer()
}

// UnimplementedTasksServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTasksServiceServer struct{}

func (UnimplementedTasksServiceServer) AddTask(context.Context, *TaskImportData) (*TaskExportData, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTask not implemented")
}
func (UnimplementedTasksServiceServer) RemoveTask(context.Context, *TaskId) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveTask not implemented")
}
func (UnimplementedTasksServiceServer) ListAllTasks(context.Context, *emptypb.Empty) (*TaskList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAllTasks not implemented")
}
func (UnimplementedTasksServiceServer) MarkTaskFinished(context.Context, *TaskId) (*TaskExportData, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkTaskFinished not implemented")
}
func (UnimplementedTasksServiceServer) mustEmbedUnimplementedTasksServiceServer() {}
func (UnimplementedTasksServiceServer) testEmbeddedByValue()                      {}

// UnsafeTasksServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TasksServiceServer will
// result in compilation errors.
type UnsafeTasksServiceServer interface {
	mustEmbedUnimplementedTasksServiceServer()
}

func RegisterTasksServiceServer(s grpc.ServiceRegistrar, srv TasksServiceServer) {
	// If the following call panics, it indicates UnimplementedTasksServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TasksService_ServiceDesc, srv)
}

func _TasksService_AddTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskImportData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksServiceServer).AddTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TasksService_AddTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksServiceServer).AddTask(ctx, req.(*TaskImportData))
	}
	return interceptor(ctx, in, info, handler)
}

func _TasksService_RemoveTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksServiceServer).RemoveTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TasksService_RemoveTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksServiceServer).RemoveTask(ctx, req.(*TaskId))
	}
	return interceptor(ctx, in, info, handler)
}

func _TasksService_ListAllTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksServiceServer).ListAllTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TasksService_ListAllTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksServiceServer).ListAllTasks(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TasksService_MarkTaskFinished_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksServiceServer).MarkTaskFinished(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TasksService_MarkTaskFinished_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksServiceServer).MarkTaskFinished(ctx, req.(*TaskId))
	}
	return interceptor(ctx, in, info, handler)
}

// TasksService_ServiceDesc is the grpc.ServiceDesc for TasksService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TasksService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tasks_pb.TasksService",
	HandlerType: (*TasksServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTask",
			Handler:    _TasksService_AddTask_Handler,
		},
		{
			MethodName: "RemoveTask",
			Handler:    _TasksService_RemoveTask_Handler,
		},
		{
			MethodName: "ListAllTasks",
			Handler:    _TasksService_ListAllTasks_Handler,
		},
		{
			MethodName: "MarkTaskFinished",
			Handler:    _TasksService_MarkTaskFinished_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
