// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x02pb\x1a\vtasks.proto\x1a\x1bgoogle/protobuf/empty.proto2\xdd\x01\n" +
	"\fTasksService\x121\n" +
	"\aAddTask\x12\x12.pb.TaskImportData\x1a\x12.pb.TaskExportData\x120\n" +
	"\n" +
	"RemoveTask\x12\n" +
	".pb.TaskId\x1a\x16.google.protobuf.Empty\x124\n" +
	"\fListAllTasks\x12\x16.google.protobuf.Empty\x1a\f.pb.TaskList\x122\n" +
	"\x10MarkTaskFinished\x12\n" +
	".pb.TaskId\x1a\x12.pb.TaskExportDataB1Z/github.com/dodocheck/go-pet-project-1/pkg/pb;pbb\x06proto3"

var file_service_proto_goTypes = []any{
	(*TaskImportData)(nil), // 0: pb.TaskImportData
	(*TaskId)(nil),         // 1: pb.TaskId
	(*emptypb.Empty)(nil),  // 2: google.protobuf.Empty
	(*TaskExportData)(nil), // 3: pb.TaskExportData
	(*TaskList)(nil),       // 4: pb.TaskList
}
var file_service_proto_depIdxs = []int32{
	0, // 0: pb.TasksService.AddTask:input_type -> pb.TaskImportData
	1, // 1: pb.TasksService.RemoveTask:input_type -> pb.TaskId
	2, // 2: pb.TasksService.ListAllTasks:input_type -> google.protobuf.Empty
	1, // 3: pb.TasksService.MarkTaskFinished:input_type -> pb.TaskId
	3, // 4: pb.TasksService.AddTask:output_type -> pb.TaskExportData
	2, // 5: pb.TasksService.RemoveTask:output_type -> google.protobuf.Empty
	4, // 6: pb.TasksService.ListAllTasks:output_type -> pb.TaskList
	3, // 7: pb.TasksService.MarkTaskFinished:output_type -> pb.TaskExportData
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_tasks_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
